language: php
sudo: false
dist: precise

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm

    - stage: style checks
      script: php vendor/bin/phpcs --standard=PSR2 src

  allow_failures:
    - php: 7.0
    - php: hhvm
    - stage: style checks

  fast_finish: false


before_script:
  - composer install

script:
  php vendor/bin/phpunit

notifications:
  email:
    - devops@uploadcare.com
    - nickzherdev@gmail.com
